name: validate_json

on:
  push:
    paths:
      - "**/*.json"
  pull_request:
    paths:
      - "**/*.json"

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34

      - name: Minify new or changed json files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == *.json ]]
              then
              echo "Creating minified version of ${file}"
              jq -c . ${file} > ${file}.mini
            fi
          done
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: '*.json *.json.mini'
          
